#!/usr/bin/env bash
# TAKEN FROM: https://github.com/Nybkox/tmux-kanagawa/blob/master/scripts/battery.sh
# setting the locale, some users have issues with different locales, this forces the correct one
export LC_ALL=en_US.UTF-8

battery_percent()
{
    echo $(pmset -g batt | grep -Eo '[0-9]?[0-9]?[0-9]%')
}

battery_status()
{
    status=$(pmset -g batt | sed -n 2p | cut -d ';' -f 2 | tr -d " ")

  case $status in
    discharging|discharging)
      echo ''
      ;;
    high|charged)
      echo ''
      ;;
    charging|charging)
      echo 'AC'
      ;;
    *)
      echo 'AC'
      ;;
  esac
}

main()
{
  bat_stat=$(battery_status)
  bat_perc=$(battery_percent)

  echo "$bat_stat $bat_perc"
}

#run main driver program
main
