#!/usr/bin/env zsh

_have() { type "$1" &>/dev/null; }

declare GROQ_API_KEY
GROQ_API_KEY="GET_YOUR_OWN_KEY"
export GROQ_API_KEY

! _have mods && echo "requires charmbracelet/mods" && exit 1

#if test -t 0; then
#  if _have glow; then
#    mods --status-text "Ummm" -f "$*" | glow
#  else
    mods --quiet --no-cache --status-text "Ummm" "$*"
#  fi
#else
#  mods --quiet "$*" | sed -E 's,[?25l [0D[2K[?25h[?1002l[?1003l,,g'
  # |sed 's/\x1B\[[0-9;\?]*[a-zA-Z]//g'
#fi
