#!/usr/bin/env bash
# setting the locale, some users have issues with different locales, this forces the correct one
export LC_ALL=en_US.UTF-8

get_ipaddr() {
  ip_en0=$(ipconfig getifaddr en0 2>/dev/null)

  # If en0 didn't return a valid IP, try en6
  if [ -z "$ip_en0" ]; then
    ip_en6=$(ipconfig getifaddr en6 2>/dev/null)
    if [ -n "$ip_en6" ]; then
      echo "$ip_en6"
    else
      echo "No IP"
    fi
  else
    echo "$ip_en0"
  fi
}

main() {
  addr="$(get_ipaddr)"
  echo "$addr"
}

#run main driver function
main
