#!/usr/bin/env bash
# setting the locale, some users have issues with different locales, this forces the correct one
export LC_ALL=en_US.UTF-8

get_ssid() {
  local wifi_network=$(ipconfig getsummary en0 | awk -F ' SSID : ' '/ SSID : / {print $2}')
  if [[ $wifi_network != "" ]]; then
    echo "$wifi_label$wifi_network"
  else
    echo 'Ethernet'
  fi
}

main() {
  network="Offline"
  if ping -q -c 1 -W 1 "google.com" &>/dev/null; then
    network="$(get_ssid)"
  fi

  echo "$network"
}

#run main driver function
main
