live_config_reload = true

import = ["~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
# decorations = "buttonless"
dynamic_padding = true
startup_mode= 'Fullscreen'

[font]
size = 13.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Light"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Light Italic"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[mouse]
hide_when_typing = true
