live_config_reload = true

import = ["~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
#decorations = "buttonless"
dynamic_padding = true
startup_mode= 'Fullscreen'

[font]
size = 15.5

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Light"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Light Italic"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[mouse]
hide_when_typing = true

[cursor]
style = "Block"
vi_mode_style = "Block"

# Map 'Command+a' to 'Ctrl-b'. This is usefull to remap the tmux default
# prefix command to a more ergonomic position.
[[keyboard.bindings]]
chars = "\u0002"
key = "a"
mods = "Command"
